"""Add team invitations

Revision ID: 0953347cba04
Revises: eb063b034dcc
Create Date: 2025-11-20 19:25:36.073062

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0953347cba04"
down_revision = "eb063b034dcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("team_invitations",
    sa.Column("team_id", sa.UUID(), nullable=False),
    sa.Column("inviter_id", sa.UUID(), nullable=False),
    sa.Column("invitee_email", sa.String(length=128), nullable=False),
    sa.Column("status", sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="invitationstatus"), nullable=False),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ),
    sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_team_invitations_invitee_email"), "team_invitations", ["invitee_email"], unique=False)
    op.create_index(op.f("ix_team_invitations_inviter_id"), "team_invitations", ["inviter_id"], unique=False)
    op.create_index(op.f("ix_team_invitations_team_id"), "team_invitations", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_invitations_team_id"), table_name="team_invitations")
    op.drop_index(op.f("ix_team_invitations_inviter_id"), table_name="team_invitations")
    op.drop_index(op.f("ix_team_invitations_invitee_email"), table_name="team_invitations")
    op.drop_table("team_invitations")
    # ### end Alembic commands ###
