"""editable_by_agent

Revision ID: 42cbd79a56f6
Revises: d2e3f4a5b6c7
Create Date: 2025-12-03 16:46:51.250916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cbd79a56f6'
down_revision = 'd2e3f4a5b6c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('editable_by_agent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'editable_by_agent')
    # ### end Alembic commands ###
