"""add api tokens table

Revision ID: 4e0e2bd61499
Revises: d2e3f4a5b6c7
Create Date: 2025-12-07 15:15:38.512707

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4e0e2bd61499"
down_revision = "d2e3f4a5b6c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("api_tokens",
    sa.Column("name", sa.String(length=256), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("token", sa.String(length=256), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_api_tokens_token"), "api_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)
    op.drop_constraint(op.f("categories_name_key"), "categories", type_="unique")
    op.drop_column("documents", "editable_by_agent")
    op.alter_column("templates", "user_id",
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("templates", "user_id",
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column("documents", sa.Column("editable_by_agent", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f("categories_name_key"), "categories", ["name"], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_token"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
