"""add archived to documents

Revision ID: 5f1f3ce72a00
Revises: 4e0e2bd61499
Create Date: 2025-12-24 12:00:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f1f3ce72a00"
down_revision = "4e0e2bd61499"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("archived", sa.Boolean(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "archived")
    # ### end Alembic commands ###
