"""add_order_to_documents

Revision ID: c842a705500c
Revises: 0953347cba04
Create Date: 2025-11-21 16:50:00.028212

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c842a705500c"
down_revision = "0953347cba04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("order", sa.Integer(), server_default="0", nullable=False))
    op.create_index(op.f("ix_documents_order"), "documents", ["order"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_order"), table_name="documents")
    op.drop_column("documents", "order")
    # ### end Alembic commands ###
