"""Create users, teams, and sessions tables

Revision ID: e0a6ffbeeb3c
Revises:
Create Date: 2025-11-20 18:46:56.875898

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e0a6ffbeeb3c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("teams",
    sa.Column("name", sa.String(length=64), nullable=False),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_table("users",
    sa.Column("username", sa.String(length=64), nullable=False),
    sa.Column("email", sa.String(length=128), nullable=False),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table("sessions",
    sa.Column("session_token", sa.String(length=255), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_sessions_session_token"), "sessions", ["session_token"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table("user_team",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("team_id", sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("user_id", "team_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_team")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_token"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
